import { projects } from '@/lib/portfolio';
import { Photo, Reveal } from '@/components/visuals';
import { VideoSection } from '@/components/video';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
export function generateStaticParams(){return projects.map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(p=>p.slug===slug);return {title:p?.title??'Story not found',description:p?.description,openGraph:{title:`${p?.title} — Still / Moving`,description:p?.description,type:'article'}};}
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const index=projects.findIndex(p=>p.slug===slug);if(index<0)notFound();const p=projects[index];const next=projects[(index+1)%projects.length];return <main id="main"><section className="project-opening"><Photo src={p.coverImage} alt={p.alt} priority sizes="100vw"/><div className="story-title"><Link className="eyebrow" href={`/work/category/${p.category.toLowerCase()}`}>{p.category.toUpperCase()} / {p.year}</Link><h1>{p.title}</h1></div></section><section className="story-info section-pad"><div className="eyebrow">{p.location.toUpperCase()}<br/>{p.category.toUpperCase()} · {p.year}<br/><br/>A STORY BY STILL / MOVING</div><Reveal><p>{p.description}</p></Reveal></section><section className="essay" aria-label={`${p.title} photo essay`}><Reveal><Photo src={p.images[1]} alt={`${p.category} study — a detail from ${p.title}`} sizes="90vw"/></Reveal><div className="essay-pair"><Reveal><Photo src={p.images[2]} alt={`${p.category} study — a closer perspective`} sizes="(max-width:700px) 80vw, 35vw"/></Reveal><Reveal><Photo src={p.images[0]} alt={p.alt} sizes="(max-width:700px) 85vw, 40vw"/></Reveal></div></section>{p.videos?.map((src,i)=><VideoSection key={src} src={src} poster={p.coverImage} title={`${p.title} — film ${i+1}`}/>)}<Link className="next-story" href={`/work/${next.slug}`} data-cursor="VIEW"><Photo src={next.coverImage} alt={next.alt} sizes="100vw"/><div><span className="eyebrow">NEXT STORY <ArrowUpRight size={14} style={{display:'inline'}}/></span><h2>{next.title}</h2><span className="eyebrow">{next.category.toUpperCase()} / {next.year}</span></div></Link></main>;}
