'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { Moon, Sun, ArrowUpRight, X, Plus } from 'lucide-react';
import { useEffect, useState, useRef } from 'react';
import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
export function Navbar() {
 const [theme, setTheme] = useState('dark'); const [menu, setMenu] = useState(false); const [scrolled, setScrolled] = useState(false); const path = usePathname(); const menuRef = useRef<HTMLDivElement>(null); const buttonRef = useRef<HTMLButtonElement>(null);
 useEffect(() => { setTheme(document.documentElement.dataset.theme || 'dark'); const media = matchMedia('(prefers-color-scheme: light)'); const sync = () => { if (!localStorage.getItem('studio-theme')) { const t = media.matches ? 'light' : 'dark'; document.documentElement.dataset.theme = t; setTheme(t); } }; media.addEventListener('change',sync); const scroll = () => setScrolled(window.scrollY > 40); window.addEventListener('scroll',scroll,{passive:true}); return () => {media.removeEventListener('change',sync);window.removeEventListener('scroll',scroll);}; }, []);
 useEffect(() => { setMenu(false); }, [path]);
 useEffect(() => { if (!menu) return; const previous = document.body.style.overflow; document.body.style.overflow='hidden'; menuRef.current?.querySelector<HTMLElement>('a')?.focus(); const key = (e: KeyboardEvent) => { if(e.key==='Escape'){setMenu(false);buttonRef.current?.focus();} if(e.key==='Tab'){const nodes=menuRef.current?.querySelectorAll<HTMLElement>('a,button'); if(!nodes?.length)return; const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}; document.addEventListener('keydown',key); return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',key);}; },[menu]);
 function toggle(){ const next=theme==='dark'?'light':'dark';setTheme(next);document.documentElement.dataset.theme=next;try{localStorage.setItem('studio-theme',next);}catch{} }
 return <><header className={`navbar ${scrolled?'scrolled':''}`}><Link className="brand-mark" href="/" aria-label="Ahmad Photography and Videography home"><img className="brand-logo brand-logo-dark" src="/brand/ahmad-logo-dark.png" alt=""/><img className="brand-logo brand-logo-light" src="/brand/ahmad-logo-light.png" alt=""/></Link><nav className="desktop-nav" aria-label="Main navigation"><Link aria-current={path.startsWith('/work')?'page':undefined} href="/work">Films</Link><Link aria-current={path==='/about'?'page':undefined} href="/about">About me</Link><Link href="/contact">Work with me <ArrowUpRight size={14}/></Link></nav><div className="nav-controls"><button className="theme-toggle" onClick={toggle} aria-label={`Switch to ${theme==='dark'?'light':'dark'} mode`}>{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}</button><button ref={buttonRef} className="menu-toggle" aria-expanded={menu} aria-controls="mobile-menu" onClick={()=>setMenu(!menu)} aria-label="Open menu"><Plus/></button></div></header><AnimatePresence>{menu&&<motion.div id="mobile-menu" ref={menuRef} role="dialog" aria-modal="true" aria-label="Navigation" className="mobile-menu" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><button className="close-menu" onClick={()=>{setMenu(false);buttonRef.current?.focus();}} aria-label="Close menu"><X/></button>{[['Films','/work'],['About me','/about'],['What I do','/services'],['Work with me','/contact']].map(([label,url],i)=><Link onClick={()=>setMenu(false)} href={url} key={url}><sup>0{i+1}</sup>{label}<ArrowUpRight/></Link>)}<p>FILMMAKER / PHOTOGRAPHER · ISLAMABAD & EVERYWHERE</p></motion.div>}</AnimatePresence></>;
}
export function CustomCursor(){const ref=useRef<HTMLDivElement>(null); const reduce=useReducedMotion();useEffect(()=>{if(reduce||!matchMedia('(pointer:fine)').matches)return;const move=(e:MouseEvent)=>{if(!ref.current)return;const target=(e.target as HTMLElement).closest('[data-cursor]');ref.current.style.transform=`translate(${e.clientX}px,${e.clientY}px)`;ref.current.style.opacity=target?'1':'0';ref.current.textContent=target?.getAttribute('data-cursor')||'';};window.addEventListener('mousemove',move);return()=>window.removeEventListener('mousemove',move);},[reduce]);return <div ref={ref} className="custom-cursor" aria-hidden="true"/>;}
export function MagneticLink({href,children}:{href:string;children:React.ReactNode}){const ref=useRef<HTMLAnchorElement>(null);const reduce=useReducedMotion();return <Link ref={ref} href={href} className="text-link" onPointerMove={e=>{if(reduce||e.pointerType!=='mouse')return;const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.06}px,${(e.clientY-r.top-r.height/2)*.12}px)`;}} onPointerLeave={e=>{e.currentTarget.style.transform='';}}>{children}<ArrowUpRight size={17}/></Link>;}
