'use client';
import Link from 'next/link';
import { ArrowDown, ArrowUpRight, ArrowLeft, ArrowRight } from 'lucide-react';
import { AnimatePresence, motion, useReducedMotion, useScroll, useTransform } from 'motion/react';
import { useRef, useState } from 'react';
import { projects, categories } from '@/lib/portfolio';
import { Photo, Reveal } from './visuals';
import { MagneticLink } from './navigation';
export function Opening(){const [active,setActive]=useState(0);const slides=[projects[4],projects[0],projects[3]];const project=slides[active];const ref=useRef<HTMLElement>(null);const reduce=useReducedMotion();const {scrollYProgress}=useScroll({target:ref,offset:['start start','end start']});const y=useTransform(scrollYProgress,[0,1],['0%','15%']);return <section ref={ref} className="opening" aria-label="Featured photography"><motion.div className="opening-image" style={reduce?{}:{y}}><AnimatePresence mode="sync"><motion.div className="opening-frame" key={project.slug} initial={{opacity:0,scale:1.035}} animate={{opacity:1,scale:1}} exit={{opacity:0}} transition={{duration:1.2}}><Photo src={project.coverImage} alt={project.alt} priority sizes="100vw"/></motion.div></AnimatePresence></motion.div><div className="opening-shade"/><div className="opening-top"><span>INDEPENDENT IMAGE MAKERS</span><span>ISLAMABAD & EVERYWHERE</span></div><div className="opening-title"><div className="eyebrow">PHOTOGRAPHY & FILM</div><h1>Life, in<br/><em>another light.</em></h1></div><div className="opening-bottom"><Link href="#selected" className="explore">Explore the work <ArrowDown size={18}/></Link><Link href={`/work/${project.slug}`} className="opening-caption" data-cursor="VIEW"><span>IN THE FRAME — 0{active+1}</span><strong>{project.title}</strong></Link><div className="slide-controls"><button aria-label="Previous featured photograph" onClick={()=>setActive((active+2)%3)}><ArrowLeft size={18}/></button><span>0{active+1} / 03</span><button aria-label="Next featured photograph" onClick={()=>setActive((active+1)%3)}><ArrowRight size={18}/></button></div></div></section>;}
export function CategoryIndex(){const [active,setActive]=useState(0);const [offset,setOffset]=useState(0);const reduce=useReducedMotion();return <section className="category-section section-pad"><div className="section-note"><span className="eyebrow">THE WAY WE SEE</span><p>Different worlds.<br/>The same curious eye.</p></div><div className="category-layout"><div className="category-list">{categories.map((category,i)=><button className={`category-row ${active===i?'active':''}`} key={category} onMouseEnter={()=>setActive(i)} onFocus={()=>setActive(i)} onClick={()=>setActive(i)} aria-pressed={active===i}><span className="index">0{i+1}</span><span>{category}</span><ArrowUpRight size={25}/></button>)}</div><div className="category-preview" onPointerMove={e=>{if(!reduce&&e.pointerType==='mouse')setOffset((e.nativeEvent.offsetX-150)*.025);}} onPointerLeave={()=>setOffset(0)}><AnimatePresence mode="wait"><motion.div key={active} initial={reduce?false:{opacity:0,clipPath:'inset(7% 0 7% 0)'}} animate={{opacity:1,clipPath:'inset(0% 0 0% 0)',x:offset}} exit={{opacity:0}} transition={{duration:.4}}><Link href={`/work/category/${categories[active].toLowerCase()}`} data-cursor="VIEW"><Photo src={projects[active].coverImage} alt={projects[active].alt} sizes="(max-width: 700px) 90vw, 38vw"/><div className="preview-caption"><span>EXPLORE {categories[active].toUpperCase()}</span><ArrowUpRight size={19}/></div></Link></motion.div></AnimatePresence></div></div></section>;}
export function SelectedWork(){const chosen=[projects[0],projects[4],projects[3],projects[1]];return <section id="selected" className="selected section-pad"><div className="section-heading"><div><span className="eyebrow">A FEW RECENT CHAPTERS / 2025—26</span><h2>Selected <em>work.</em></h2></div><MagneticLink href="/work">View the full archive</MagneticLink></div><div className="selected-grid">{chosen.map((p,i)=><Reveal key={p.slug} className={`project-preview project-${i}`}><Link href={`/work/${p.slug}`} data-cursor="VIEW"><Photo src={p.coverImage} alt={p.alt}/><div className="project-caption"><h3>{p.title}</h3><span>{p.category.toUpperCase()} / {p.year}</span><ArrowUpRight size={19}/></div></Link></Reveal>)}</div></section>;}
